### ISSUE TITLE
Can we have logger configurable?

### ISSUE THREAD

**Issue by shrinathprabhu** [tristanisham/logysia#7]
In current scenario I don't want the logger to log IP to the console. It's using X-Forwarded-For header and logging out IP. Can we make this configurable?

**Comment by dodas** [comment]
+1 for making the logging configurable.
a simple callback that gets`Context & { durationString: string; durationMs: number }` and logs the message as a side effect would be sufficient. This would also allow to use custom loggers like `winston` instead of plain `console.log`.
I can work on this, if we agree on implementation.

**Comment by shrinathprabhu** [comment]
cc: @tristanisham

**Comment by tristanisham** [comment]
Sure. I can look into adding a configuration option.

**Comment by tristanisham** [comment]
Added in v0.1.1
```ts
interface Options {
    logIP: boolean
}

logger({logIP: false})
```

**Comment by shrinathprabhu** [comment]
Thanks
